[font.bold]
family = "Hack Nerd Font"
style = "Bold"

[font.italic]
family = "Hack Nerd Font"
style = "MediumItalic"

[font.normal]
family = "Hack Nerd Font"
style = "Medium"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 5
y = 5

[window]
blur = true
opacity = 1.0

[cursor.style]
blinking = "Always"
